# Generated by Django 2.0.6 on 2018-06-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20180614_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
